# Generated by Django 2.2.28 on 2025-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(to='censura.Movie'),
        ),
    ]
