# Generated by Django 2.2.28 on 2025-03-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('censura', '0002_movie_slug'),
        ('censura', '0002_userprofile_likes'),
    ]

    operations = [
    ]
