# Generated by Django 2.2.28 on 2025-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censura', '0003_merge_20250313_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='censura.Movie'),
        ),
    ]
